SELECT TO_CHAR(DATE, 'Day') AS DAY,
	GENRE,
	(CASE WHEN NO_OF_STUDENTS IS NULL THEN G_S.MAX_STUDENTS
			ELSE G_S.MAX_STUDENTS - NO_OF_STUDENTS
		END) AS SLOTS
FROM
	(SELECT S.ID, DATE, GENRE
		FROM TIME_SLOT AS T_S,
			ENSEMBLE AS E,
			SESSION AS S
		WHERE S.TIME_SLOT_ID = T_S.ID
			AND S.ID = E.ID
			AND EXTRACT(WEEK FROM DATE) = EXTRACT(WEEK FROM CURRENT_DATE) + 1) AS S
LEFT JOIN GROUP_SESSION AS G_S ON S.ID = G_S.ID
LEFT JOIN
	(SELECT G_S.ID,
			COUNT(*) AS NO_OF_STUDENTS
		FROM ATTENDEES,
			GROUP_SESSION AS G_S
		WHERE ATTENDEES.SESSION_ID = G_S.ID
		GROUP BY G_S.ID) AS A ON A.ID = S.ID
ORDER BY date,
	GENRE