SELECT * FROM
(SELECT T.ID,
	P.NAME,
	COUNT(S.ID) AS NO_OF_LESSONS
FROM TEACHER AS T
LEFT JOIN PERSON AS P ON T.ID = P.ID
LEFT JOIN
	(SELECT SESSION.*
		FROM SESSION
		LEFT JOIN TIME_SLOT ON SESSION.TIME_SLOT_ID = TIME_SLOT.ID
		WHERE EXTRACT(MONTH FROM TIME_SLOT.DATE) = EXTRACT(MONTH FROM CURRENT_DATE)
			AND EXTRACT(YEAR FROM TIME_SLOT.DATE) = EXTRACT(YEAR FROM CURRENT_DATE)
			AND EXTRACT(DAY FROM TIME_SLOT.DATE) < EXTRACT(DAY FROM CURRENT_DATE)) 
	AS S ON P.ID = S.TEACHER_ID
GROUP BY T.ID,
	P.NAME) AS LESSONS
WHERE LESSONS.NO_OF_LESSONS > 0
ORDER BY NO_OF_LESSONS DESC