SELECT SIBLINGS, 
	COUNT(SIBLINGS) AS GROUPS 
	FROM (SELECT COUNT(SIBLINGS.*) AS SIBLINGS 
		  	FROM STUDENT LEFT JOIN 
		  		SIBLINGS ON SIBLINGS.STUDENT_ID = STUDENT.ID 
		  	GROUP BY STUDENT.ID)  
		GROUP BY SIBLINGS
		ORDER BY SIBLINGS;